### ISSUE TITLE
mp100 dataset problem

### ISSUE THREAD

**Issue by binxlin** [orhir/EdgeCape#2]
@orhir Hello,I want to know how you obtained the image files for the 'fly_body' and 'locust_body' classes in the 'deepposekit' dataset when preparing the MP100 dataset. Because when following the official GitHub instructions, I only found the .h5 files, and despite trying many methods, I was unable to perform the release operation on the .h5 files. I would appreciate any help you can provide! Thank you!

**Comment by orhir** [comment]
Hi, you should extract the h5 images.
You can use simple python scripts such as from [this thread](https://stackoverflow.com/questions/66874324/how-to-extract-individual-jpeg-images-from-a-hdf5-file):
```
with h5py.File('yourfile.h5','r') as h5f:
    for i in range(h5f['images'].shape[0]):
        img_arr = h5f['images'][i]
        cv2.imwrite(f'{i}.jpg',img_arr)
```
